# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='email_status',
            field=models.CharField(blank=True, choices=[('0', 'Queued'), ('1', 'Sended'), ('2', 'Failed')], default='', max_length=1, null=True, verbose_name='Email Status'),
        ),
    ]
