# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_promotion_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='email_status',
            field=models.CharField(blank=True, choices=[('0', 'Queued'), ('1', 'Sended')], default='', max_length=1, null=True, verbose_name='Email Status'),
        ),
    ]
